// <auto-generated />
using System;
using Adni.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Adni.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220809215757_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Adni.Domain.Entities.CompaniesList", b =>
                {
                    b.Property<Guid>("CompaniesListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CompaniesListId");

                    b.ToTable("companiesLists");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompaniesListId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyCigle")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyFocal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyPhonenumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProspectorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesListId");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeesListId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsappNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeesListId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Adni.Domain.Entities.EmployeesList", b =>
                {
                    b.Property<Guid>("EmployeesListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeesRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeesListId");

                    b.ToTable("employeesLists");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Company", b =>
                {
                    b.HasOne("Adni.Domain.Entities.CompaniesList", null)
                        .WithMany("Companies")
                        .HasForeignKey("CompaniesListId");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Adni.Domain.Entities.EmployeesList", null)
                        .WithMany("Employees")
                        .HasForeignKey("EmployeesListId");
                });

            modelBuilder.Entity("Adni.Domain.Entities.CompaniesList", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Adni.Domain.Entities.EmployeesList", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
