// <auto-generated />
using System;
using Adni.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adni.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Adni.Domain.Entities.CompaniesList", b =>
                {
                    b.Property<Guid>("CompaniesListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CompaniesListId");

                    b.ToTable("companiesLists");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompaniesListId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyCigle")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyFocal")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyPhonenumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProspectorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesListId");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HeadDepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProspectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.HasIndex("ProspectionId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DoB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeesListId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsappNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeesListId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Adni.Domain.Entities.EmployeesList", b =>
                {
                    b.Property<Guid>("EmployeesListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeesRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeesListId");

                    b.ToTable("employeesLists");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Field", b =>
                {
                    b.Property<Guid>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldCigle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProspectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("FieldId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProspectionId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Prospection", b =>
                {
                    b.Property<Guid>("ProspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeProspectorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlacesDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProspectionsListId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProspectionId");

                    b.HasIndex("ProspectionsListId");

                    b.ToTable("prospections");
                });

            modelBuilder.Entity("Adni.Domain.Entities.ProspectionsList", b =>
                {
                    b.Property<Guid>("ProspectionsListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .HasColumnType("TEXT");

                    b.HasKey("ProspectionsListId");

                    b.ToTable("prospectionsList");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Company", b =>
                {
                    b.HasOne("Adni.Domain.Entities.CompaniesList", null)
                        .WithMany("Companies")
                        .HasForeignKey("CompaniesListId");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Department", b =>
                {
                    b.HasOne("Adni.Domain.Entities.Prospection", null)
                        .WithMany("DesiredDepartmentsList")
                        .HasForeignKey("ProspectionId");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Adni.Domain.Entities.EmployeesList", null)
                        .WithMany("Employees")
                        .HasForeignKey("EmployeesListId");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Field", b =>
                {
                    b.HasOne("Adni.Domain.Entities.Department", null)
                        .WithMany("Fields")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adni.Domain.Entities.Prospection", null)
                        .WithMany("DesiredFields")
                        .HasForeignKey("ProspectionId");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Prospection", b =>
                {
                    b.HasOne("Adni.Domain.Entities.ProspectionsList", null)
                        .WithMany("ProspectionRecap")
                        .HasForeignKey("ProspectionsListId");
                });

            modelBuilder.Entity("Adni.Domain.Entities.CompaniesList", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Department", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Adni.Domain.Entities.EmployeesList", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Adni.Domain.Entities.Prospection", b =>
                {
                    b.Navigation("DesiredDepartmentsList");

                    b.Navigation("DesiredFields");
                });

            modelBuilder.Entity("Adni.Domain.Entities.ProspectionsList", b =>
                {
                    b.Navigation("ProspectionRecap");
                });
#pragma warning restore 612, 618
        }
    }
}
